import { StrictMode, useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "./supabase";
import "./styles.css";

type Finding = { id: string; category: string; kind: string; text: string; sourceMessageIds: string[] };
type Draft = { version: number; title: string; summary: string; findings: Finding[]; followUpNotes: Array<{ text: string; sourceMessageIds: string[] }> };
type Store = { id: string; name: string; city: string; timezone: string };
type Visit = { id: string; storeId: string; authorId: string; state: "collecting" | "ready_for_review" | "validated" | "cancelled"; startedAt: string; validatedAt?: string; draft?: Draft };
type User = { id: string; displayName: string; storeIds: string[] };
type Message = { id: string; kind: "text" | "audio" | "correction" | "procedural_question" | "validation"; text?: string; transcript?: string; audioPath?: string; processingStatus: string; processingError?: string; receivedAt: string };
type VisitDetail = { visit: Visit; store: Store; author: { id: string; displayName: string }; messages: Message[] };
type Page = "overview" | "stores" | "visits" | "reports";
const API = "http://localhost:3001/api";
const label = (value: string) => value.replace(/_/g, " ");
const dateTime = (value?: string) => value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
const dateOnly = (value?: string) => value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(new Date(value)) : "—";

function App() {
  const demoMode = import.meta.env.VITE_ENABLE_DEMO_MODE === "true";
  const [userId, setUserId] = useState("user_anika");
  const [session, setSession] = useState<Session | null>(); const [authError, setAuthError] = useState("");
  const [user, setUser] = useState<User>(); const [stores, setStores] = useState<Store[]>([]); const [visits, setVisits] = useState<Visit[]>([]);
  const [page, setPage] = useState<Page>("overview"); const [selected, setSelected] = useState<VisitDetail>();
  const [storeFilter, setStoreFilter] = useState("all"); const [stateFilter, setStateFilter] = useState("all"); const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [audioUrls, setAudioUrls] = useState<Record<string, string>>({});
  const request = async <T,>(path: string): Promise<T> => { const headers: Record<string, string> = session ? { authorization: `Bearer ${session.access_token}` } : { "x-demo-user": userId }; const response = await fetch(`${API}${path}`, { headers }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Request failed"); return body as T; };
  async function load() { setLoading(true); setError(""); try { const [nextUser, nextStores, nextVisits] = await Promise.all([request<User>("/me"), request<Store[]>("/stores"), request<Visit[]>("/visits")]); setUser(nextUser); setStores(nextStores); setVisits(nextVisits); setSelected(undefined); setAudioUrls({}); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load dashboard data."); } finally { setLoading(false); } }
  useEffect(() => {
    if (demoMode || !supabase) { setSession(null); return; }
    void supabase.auth.getSession().then(({ data }) => setSession(data.session));
    const { data: listener } = supabase.auth.onAuthStateChange((_event, nextSession) => setSession(nextSession));
    return () => listener.subscription.unsubscribe();
  }, [demoMode]);
  useEffect(() => { if (demoMode || session) void load(); }, [userId, session?.access_token, demoMode]);
  const filtered = useMemo(() => visits.filter((visit) => { const store = stores.find((item) => item.id === visit.storeId); return (storeFilter === "all" || visit.storeId === storeFilter) && (stateFilter === "all" || visit.state === stateFilter) && `${store?.name ?? ""} ${visit.draft?.title ?? ""} ${visit.draft?.summary ?? ""}`.toLowerCase().includes(query.toLowerCase()); }), [visits, stores, storeFilter, stateFilter, query]);
  const openVisit = async (id: string) => { setLoading(true); setError(""); try { setSelected(await request<VisitDetail>(`/visits/${id}`)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not open this visit."); } finally { setLoading(false); } };
  const playAudio = async (id: string) => { try { const result = await request<{ url: string }>(`/messages/${id}/audio-url`); setAudioUrls((current) => ({ ...current, [id]: result.url })); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not open the voice note."); } };
  const copyReport = (draft: Draft) => void navigator.clipboard.writeText(`${draft.title}\n\n${draft.summary}\n\nFindings:\n${draft.findings.map((finding) => `• ${finding.text}`).join("\n")}${draft.followUpNotes.length ? `\n\nFollow-up notes:\n${draft.followUpNotes.map((note) => `• ${note.text}`).join("\n")}` : ""}`);
  if (!demoMode && !supabase) return <AuthScreen error="Supabase Auth is not configured yet. Add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to the root .env file." onSubmit={() => undefined} />;
  if (!demoMode && session === undefined) return <main className="auth-shell"><section className="auth-card">Checking your secure session…</section></main>;
  if (!demoMode && !session) return <AuthScreen error={authError} onSubmit={async (email, password) => { setAuthError(""); const { error: signInError } = await supabase!.auth.signInWithPassword({ email, password }); if (signInError) setAuthError(signInError.message); }} />;
  if (selected) return <Detail detail={selected} loading={loading} error={error} audioUrls={audioUrls} onBack={() => setSelected(undefined)} onPlay={playAudio} onCopy={copyReport} />;
  const active = filtered.filter((visit) => ["collecting", "ready_for_review"].includes(visit.state)); const validated = filtered.filter((visit) => visit.state === "validated"); const awaiting = filtered.filter((visit) => visit.state === "ready_for_review");
  return <main className="shell"><header className="topbar"><div><span className="eyebrow">AGENT RIVO</span><h1>Field visit reporting</h1></div><div className="user-control"><span>{user?.displayName ?? "Loading…"}</span>{demoMode ? <select aria-label="Development user" value={userId} onChange={(event) => setUserId(event.target.value)}><option value="user_anika">Anika Rao</option><option value="user_noah">Noah Bennett</option></select> : <button onClick={() => void supabase!.auth.signOut()}>Sign out</button>}</div></header><nav aria-label="Dashboard navigation">{(["overview", "stores", "visits", "reports"] as Page[]).map((item) => <button className={page === item ? "nav-active" : "nav-button"} key={item} onClick={() => setPage(item)}>{item}</button>)}</nav><section className="filters"><label>Store<select value={storeFilter} onChange={(event) => setStoreFilter(event.target.value)}><option value="all">All accessible stores</option>{stores.map((store) => <option key={store.id} value={store.id}>{store.name}</option>)}</select></label><label>State<select value={stateFilter} onChange={(event) => setStateFilter(event.target.value)}><option value="all">All states</option><option value="collecting">Collecting</option><option value="ready_for_review">Awaiting validation</option><option value="validated">Validated</option><option value="cancelled">Cancelled</option></select></label><label className="search">Search<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Store or report text" /></label><button onClick={load}>Refresh data</button></section>{error && <section className="notice error"><span>{error}</span><button onClick={load}>Retry</button></section>}{loading ? <section className="panel loading">Loading real visit data…</section> : <Dashboard page={page} stores={stores} visits={filtered} validated={validated} active={active} awaiting={awaiting} onOpen={openVisit} />}</main>;
}

function AuthScreen({ error, onSubmit }: { error: string; onSubmit: (email: string, password: string) => void }) { const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); return <main className="auth-shell"><form className="auth-card" onSubmit={(event) => { event.preventDefault(); onSubmit(email, password); }}><span className="eyebrow">AGENT RIVO</span><h1>Sign in</h1><p>Use your regional-manager test account.</p><label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} required /></label>{error && <p className="error-text">{error}</p>}<button type="submit">Sign in securely</button></form></main>; }

function Dashboard({ page, stores, visits, validated, active, awaiting, onOpen }: { page: Page; stores: Store[]; visits: Visit[]; validated: Visit[]; active: Visit[]; awaiting: Visit[]; onOpen: (id: string) => void }) { const storeFor = (id: string) => stores.find((store) => store.id === id); if (page === "stores") return <section className="store-grid">{stores.map((store) => { const latest = visits.find((visit) => visit.storeId === store.id && visit.state === "validated"); return <article className="store-card" key={store.id}><span className="eyebrow">{store.city}</span><h2>{store.name}</h2><p>Latest validated visit: {dateOnly(latest?.startedAt)}</p><button onClick={() => latest && onOpen(latest.id)} disabled={!latest}>Open latest visit</button></article>; })}</section>; if (page === "reports") return <Table title="Validated report library" visits={validated} storeFor={storeFor} onOpen={onOpen} empty="No validated reports match these filters." />; if (page === "visits") return <Table title="Visit history" visits={visits} storeFor={storeFor} onOpen={onOpen} empty="No visits match these filters." />; return <><section className="cards"><Metric value={stores.length} label="Accessible stores" /><Metric value={validated.length} label="Validated reports" /><Metric value={active.length} label="Active visits" /><Metric value={awaiting.length} label="Awaiting validation" /></section><Table title="Recent visits" visits={visits.slice(0, 8)} storeFor={storeFor} onOpen={onOpen} empty="No visits match these filters." /></>; }
function Metric({ value, label: text }: { value: number; label: string }) { return <article className="metric"><strong>{value}</strong><span>{text}</span></article>; }
function Table({ title, visits, storeFor, onOpen, empty }: { title: string; visits: Visit[]; storeFor: (id: string) => Store | undefined; onOpen: (id: string) => void; empty: string }) { return <section className="panel"><div className="panel-heading"><h2>{title}</h2><span className="muted">{visits.length} shown</span></div>{visits.length === 0 ? <p className="muted">{empty}</p> : <div className="table-wrap"><table><thead><tr><th>Date</th><th>Store</th><th>State</th><th>Report</th><th /></tr></thead><tbody>{visits.map((visit) => <tr key={visit.id}><td>{dateTime(visit.startedAt)}</td><td>{storeFor(visit.storeId)?.name ?? visit.storeId}</td><td><span className={`badge ${visit.state}`}>{label(visit.state)}</span></td><td>{visit.draft ? `${visit.draft.title} · v${visit.draft.version}` : "No draft yet"}</td><td><button className="link-button" onClick={() => onOpen(visit.id)}>Open</button></td></tr>)}</tbody></table></div>}</section>; }
function Detail({ detail, loading, error, audioUrls, onBack, onPlay, onCopy }: { detail: VisitDetail; loading: boolean; error: string; audioUrls: Record<string, string>; onBack: () => void; onPlay: (id: string) => void; onCopy: (draft: Draft) => void }) { const { visit, store, author, messages } = detail; const draft = visit.draft; return <main className="shell"><button className="back" onClick={onBack}>← Back to dashboard</button><header className="detail-header"><div><span className="eyebrow">{store.city}</span><h1>{store.name}</h1><p>{dateTime(visit.startedAt)} · {author.displayName}</p></div><div><span className={`badge ${visit.state}`}>{label(visit.state)}</span>{draft && <p className="version">Draft v{draft.version}</p>}</div></header>{error && <section className="notice error">{error}</section>}{loading ? <section className="panel loading">Loading visit details…</section> : <section className="detail-grid"><section className="panel"><div className="panel-heading"><h2>Source timeline</h2><span className="muted">{messages.length} inputs</span></div>{messages.length === 0 ? <p className="muted">No recorded inputs.</p> : <ol className="timeline">{messages.map((message) => <li key={message.id}><div className="timeline-meta"><strong>{label(message.kind)}</strong><time>{dateTime(message.receivedAt)}</time></div><p>{message.transcript ?? message.text ?? "Voice note received"}</p>{message.audioPath && <><span className={`processing ${message.processingStatus}`}>{message.processingStatus}</span>{!audioUrls[message.id] && <button className="link-button" onClick={() => onPlay(message.id)}>Play original audio</button>}{audioUrls[message.id] && <audio controls src={audioUrls[message.id]} />}{message.processingError && <p className="error-text">Transcription failed: {message.processingError}</p>}</>}</li>)}</ol>}<p className="whatsapp-note">Continue this visit through WhatsApp. Refresh this dashboard after sending a message.</p></section><section className="panel report"><div className="panel-heading"><h2>{visit.state === "validated" ? "Validated report" : "Current draft"}</h2>{draft && <div className="inline-actions"><button onClick={() => onCopy(draft)}>Copy report</button><button onClick={() => window.print()}>Print</button></div>}</div>{!draft ? <p className="muted">No report has been prepared yet.</p> : <Report draft={draft} validatedAt={visit.validatedAt} messages={messages} />}</section></section>}</main>; }
function Report({ draft, validatedAt, messages }: { draft: Draft; validatedAt?: string; messages: Message[] }) { return <article className="report-content"><h3>{draft.title}</h3>{validatedAt && <p className="validated-at">Validated {dateTime(validatedAt)}</p>}<h4>Overview</h4><p>{draft.summary}</p><h4>Findings</h4>{draft.findings.length ? <ul>{draft.findings.map((finding) => <li key={finding.id}><strong>{label(finding.category)}:</strong> {finding.text}<small>Sources: {finding.sourceMessageIds.map((id) => messages.findIndex((message) => message.id === id) + 1).filter((index) => index > 0).join(", ") || "recorded input"}</small></li>)}</ul> : <p className="muted">No factual observations accepted yet.</p>}{draft.followUpNotes.length > 0 && <><h4>Follow-up mentioned</h4><ul>{draft.followUpNotes.map((note, index) => <li key={index}>{note.text}</li>)}</ul></>}</article>; }
createRoot(document.getElementById("root")!).render(<StrictMode><App /></StrictMode>);
